#!/bin/bash

# Twenty Object Schema Sync
# Since GraphQL doesn't expose object creation, we need to use the internal metadata tables

LOCAL_URL="http://localhost:3002"
CLOUD_URL="https://divisionshowroom.twenty.com"
LOCAL_KEY="eyJhbGciOiJFUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IjQwN2U0ZmRlLWMwMzItNDdlOS04NWNiLTVhYTQ0ZTI3YTMxNiJ9.eyJzdWIiOiI1Mjk1Y2UwYy1jYmMyLTRlZWUtOWMwOS02OTcwNmM4MmI3OGUiLCJ0eXBlIjoiQVBJX0tFWSIsIndvcmtzcGFjZUlkIjoiNTI5NWNlMGMtY2JjMi00ZWVlLTljMDktNjk3MDZjODJiNzhlIiwiaWF0IjoxNzgyNDk2NDk2LCJleHAiOjQ5MzYwOTY0OTUsImp0aSI6IjJkMGEzYTQyLTM5ZjktNDc0Yi1hMjc5LWY5NTAxYzk5YzI1OCJ9.35iUvkIpbtF7a-UMYRB446eLwdtaf5fK04XKt3vO0deBXeKQu1TidvWSSGMkhWJAFSg86fWXEHozm3DZcfJ0_Q"
CLOUD_KEY="eyJhbGciOiJFUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IjBlNjg0ZTBhLTgzYTUtNDZkNS1iYWI1LTk5NDhiMTkyOWMwNCJ9.eyJzdWIiOiI1MzA2ZjM2Zi0yODg3LTQ4MWUtYTZjYS0zYWYwOWMxYWQyZWMiLCJ0eXBlIjoiQVBJX0tFWSIsIndvcmtzcGFjZUlkIjoiNTMwNmYzNmYtMjg4Ny00ODFlLWE2Y2EtM2FmMDljMWFkMmVjIiwiaWF0IjoxNzgyOTY2MTQ1LCJleHAiOjQ5MzY1NjYxMzksImp0aSI6ImYwOTIwNmNjLTgyNzMtNDUzYy04OGQ0LWRiZjkzYThmYmI5YSJ9.hY5A3mFECOm_jCc5HqIPRZ2YJmqBOUDoMA4TPllwp6mSwPUMenoA7Qv-OadFGk14QS1sHuRUPreKiSR5pX49Ag"

echo "⚠️  Schema sync requires database access."
echo ""
echo "Since Twenty's GraphQL API doesn't expose object/field creation,"
echo "we need to manually add the missing fields to the cloud instance."
echo ""
echo "Option 1: Database Access"
echo "  If you have direct database access to the cloud instance:"
echo "  - Connect to divisionshowroom.twenty.com's Postgres DB"
echo "  - Run migrations from local database schema"
echo ""
echo "Option 2: Manual UI (Recommended)"
echo "  1. Go to https://divisionshowroom.twenty.com/settings/objects"
echo "  2. Find 'Pull' object"
echo "  3. Add missing fields:"
echo "     - stage (Enum: OUT, RETURN, LOAN)"
echo "     - deliveryNote (Text)"
echo "     - returnDate (Date)"
echo "     - creditGiven (Checkbox)"
echo "     - clientId (Relation to Person)"
echo ""
echo "  4. Create new 'Inventory Item' object with fields:"
echo "     - designer (Text)"
echo "     - itemId (Text)"
echo "     - itemType (Enum)"
echo "     - season (Enum)"
echo "     - status (Enum)"
echo "     - retailPrice (Currency)"
echo "     - wholesalePrice (Currency)"
echo "     - loanFee (Currency)"
echo "     - pullId (Relation to Pull)"
echo ""
echo "After completing step 2, run the data sync again."
